/*
 * Copyright 2022 Infineon Technologies AG.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package com.infineon.nfcbpsk.services.brandverification;

import android.os.Parcel;
import android.os.Parcelable;

import org.json.JSONException;
import org.json.JSONObject;

/**
 * Model class to store the response parameters of generate mutual authentication command 
 */
public class MutualAuthGenerateResponse implements Parcelable {

    public static final Creator<MutualAuthGenerateResponse> CREATOR = new Creator<MutualAuthGenerateResponse>() {
        @Override
        public MutualAuthGenerateResponse createFromParcel(Parcel in) {
            return new MutualAuthGenerateResponse(in);
        }

        @Override
        public MutualAuthGenerateResponse[] newArray(int size) {
            return new MutualAuthGenerateResponse[size];
        }
    };

    /**
     * Session ID generated by the server
     */
    public String sessionID;

    /**
     * Mutual auth command data in hex string format
     */
    public String commandData;

    /**
     * Initializes based on the JSON response received from the server
     *
     * @param jsonData          JSON response from generate-ma API
     * @throws JSONException    Exception thrown if the JSON doesn't have required parameters
     */
    public MutualAuthGenerateResponse(String jsonData) throws JSONException {
        JSONObject jsonObject = new JSONObject(jsonData);
        this.sessionID = jsonObject.getString("SessionID");
        this.commandData = jsonObject.getString("CommandData");
    }

    /**
     * Initializes based on the parcelable input
     *
     * @param in Parcelable input
     */
    protected MutualAuthGenerateResponse(Parcel in) {
        sessionID = in.readString();
        commandData = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(sessionID);
        dest.writeString(commandData);
    }
}
